---
- name: Install Applications on Ubuntu
  hosts: webservers
  become: true

  tasks:
  - name: Install Nginx
    apt:
      name: nginx
      state: present

  - name: Install MySQL client
    apt:
      name: mysql-client
      state: present

