---

- hosts: all
  become: yes
  tasks:
  -  name: Install zabbix-agent on Centos-7
     yum:
        name=zabbix-agent
        state=latest
     when:
        ansible_os_family == "RedHat"
     notify:
        zabbix-agent systemd
  - name: Install redis on Ubuntu
     apt:
        name=redis
        state=latest
     when:
        ansible_os_family == "Debian"
     notify:
        zabbix-agent systemd
  handlers:
  - name:
        zabbix-agent systemd
    systemd:
     name: zabbix-agent.service
     enabled: yes
     state: started
