---

- hosts: web
  become: yes
  tasks:

  - name: bind on Ubuntu 
    apt:
        name=bind9
        state=latest
    when:
        ansible_os_family == "Debian"

    notify:
        bind systemd
  handlers:
  - name: bind systemd
    systemd:
     name:
        bind9.service
     enabled: yes
     state: started

