---
- hosts: web
  gather_facts: yes

  pre_tasks:

    - name: update apt cache if needed
      become: yes
      apt:
        update_cache=yes
        cache_valid_time=3600

  tasks:

    - name: Download Filebeat Package
      copy:
         src: /etc/ansible/common/files/filebeat-7.17.8-amd64.deb
         dest: /home/learn
         owner: learn
         group: learn
         mode: 0644


    - name: Install FileBeat Deb Package
      become: yes
      apt:
        deb: /home/learn/filebeat-7.17.8-amd64.deb
    
    - name: Remove FileBeat YAML File
      become: yes
      file:
        path: /etc/filebeat/filebeat.yml
        state: absent
    
    - name: Create New FileBeat YAML File
      become: yes
      file:
         path: /etc/filebeat/filebeat.yml
         state: touch

    - name: Add FileBeat YAML Configuration
      become: yes
      blockinfile:
         path: /etc/filebeat/filebeat.yml
         marker: ""
         block: |
           filebeat.inputs:
           - type: log
             paths:
              - /var/log/*.log
           output.logstash:
              hosts: ["158.160.30.121:5044"]
      
    - name: Start FileBeat Service
      become: yes
      service:
        name: filebeat
        state: started
