---

- hosts: web
  become: yes
  tasks:

  - name: nginx on Ubuntu 
    apt:
        name=nginx
        state=latest
    when:
        ansible_os_family == "Debian"

    notify:
        nginx systemd
  handlers:
  - name: nginx systemd
    systemd:
     name:
        nginx.service
     enabled: yes
     state: started

  - name: apache2 on Ubuntu 
    apt:
        name=apache2
        state=latest
    when:
        ansible_os_family == "Debian"

    notify:
        apache2 systemd
  handlers:
  - name: apache2 systemd
    systemd:
     name:
        apache2.service
     enabled: yes
